version: '3.9'
services:
  app:
    build:
      context: .
    command: [ "/wait-for-it.sh", "db", "/entrypoint.sh" ]
    expose:
      - 8000
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
    depends_on:
      - db
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=123@456
  db:
    image: postgres:16-alpine
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U test" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - '5433:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=123@456

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/app/static
      - ./media:/app/media


volumes:
  static_volume:
  media_volume:
  postgres-data: