# Generated by Django 5.0.7 on 2024-11-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MBA', models.CharField(blank=True, choices=[('IR1B', 'IR1B'), ('IR2B', 'IR2B'), ('IR3B', 'IR3B')], max_length=20)),
                ('item_id', models.CharField(blank=True, max_length=100)),
                ('container_id', models.CharField(blank=True, max_length=100)),
                ('ic_date', models.DateField(blank=True, null=True)),
                ('ic_code', models.CharField(blank=True, choices=[('DI', 'DI'), ('FW', 'FW'), ('GA', 'GA')], max_length=20)),
                ('from_mba', models.CharField(blank=True, choices=[('IR1B', 'IR1B'), ('IR2B', 'IR2B'), ('IR3B', 'IR3B')], max_length=20)),
                ('mdc', models.CharField(blank=True, choices=[('BQ1F', 'BQ1F'), ('BQ1G', 'BQ1G')], max_length=20)),
                ('obl_code', models.CharField(blank=True, choices=[('P', 'P')], max_length=20)),
                ('to_mba', models.CharField(blank=True, choices=[('IR1B', 'IR1B'), ('IR2B', 'IR2B'), ('IR3B', 'IR3B')], max_length=20)),
                ('no_of_items', models.PositiveIntegerField(default=1)),
                ('elt_code', models.CharField(blank=True, choices=[('D', 'D'), ('E', 'E'), ('N', 'N'), ('P', 'P'), ('T', 'T')], max_length=2)),
                ('uo2_wf', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('elt_wf', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('enr', models.DecimalField(decimal_places=2, default=1.6, max_digits=5)),
                ('iso_code', models.CharField(blank=True, max_length=2)),
                ('iso_wf', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('burnup', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('mb', models.CharField(blank=True, max_length=2)),
                ('fuel_type', models.CharField(blank=True, choices=[('16', '16'), ('24', '24'), ('24B20', '24B20'), ('24B36', '24B36'), ('36', '36'), ('36B20', '36B20'), ('36B36', '36B36'), ('40', '40'), ('40B20', '40B20'), ('40B36', '40B36'), ('40B50', '40B50')], max_length=6, null=True, verbose_name='Fuel Type')),
                ('notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Notes')),
                ('mat_descr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mat Descr')),
                ('total_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total WT (KG)')),
                ('date_of_production', models.DateField(verbose_name='Date Of Production')),
                ('cps_ar_bar', models.CharField(blank=True, max_length=100, null=True, verbose_name='CPS AR/BAR')),
                ('drawing_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Drawing NO')),
                ('product_images', models.FileField(blank=True, upload_to='product_images/')),
            ],
            options={
                'verbose_name': 'Inset Receipt',
                'verbose_name_plural': 'Inset Receipts',
            },
        ),
    ]
