# Generated by Django 5.0.7 on 2024-11-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_field1', models.CharField(max_length=100)),
                ('custom_field2', models.IntegerField()),
            ],
        ),
    ]
