# Generated by Django 5.0.7 on 2024-11-07 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='custom_field2',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='custom_field1',
            new_name='name',
        ),
    ]
